# Generated by Django 3.1.1 on 2020-09-10 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('attendedBy', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
