# Generated by Django 3.1.1 on 2020-09-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_meetingheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendaHeader', models.CharField(max_length=255)),
                ('agendaMainText', models.CharField(max_length=255)),
            ],
        ),
    ]
