# Generated by Django 3.1.1 on 2020-09-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_agendaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='underMeeting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='meeting.meeting'),
        ),
    ]
